/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package maingui;
import pkgreturn.ReturnMenuGUI;
import vegetableapp.VegPanel;
import sustainability.SustainabilityGUI;
/**
 *
 * @author omgit
 */
public class LandingPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LandingPage.class.getName());

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReturnButton = new javax.swing.JButton();
        SustainButton = new javax.swing.JButton();
        VegetableButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReturnButton.setText("Click here to enter ReTurn");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        SustainButton.setText("Click here to enter Sustainability");
        SustainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SustainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SustainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        VegetableButton.setText("Click here to enter Vegetable");
        VegetableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegetableButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VegetableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OOP vegApp bg2.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
       ReturnMenuGUI returnGUI = new ReturnMenuGUI();
       returnGUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void SustainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SustainButtonActionPerformed
        // TODO add your handling code here:
        SustainabilityGUI myGUI = new SustainabilityGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_SustainButtonActionPerformed

    private void VegetableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegetableButtonActionPerformed
        // TODO add your handling code here:
        VegPanel sqGUI = new VegPanel();
        sqGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_VegetableButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LandingPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SustainButton;
    private javax.swing.JButton VegetableButton;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
