/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package returndemo;

/**
 *
 * @author Thitsar Thway
 */
public class AddItemScreenGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddItemScreenGUI.class.getName());

    /**
     * Creates new form AddItemScreenGUI
     */
    public AddItemScreenGUI() {
        initComponents();
        setSize(500,300);
        calculatedDepositLbl.setVisible(false);
        displayDepositLbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeRBGroup = new javax.swing.ButtonGroup();
        sizeRBGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingCountTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pendingDepositTA = new javax.swing.JTextArea();
        pendingCountLbl = new javax.swing.JLabel();
        pendingDepositLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        sizeLbl = new javax.swing.JLabel();
        quantityLbl = new javax.swing.JLabel();
        calculatedDepositLbl = new javax.swing.JLabel();
        canRB = new javax.swing.JRadioButton();
        bottleRB = new javax.swing.JRadioButton();
        smallRB = new javax.swing.JRadioButton();
        largeRB = new javax.swing.JRadioButton();
        displayDepositLbl = new javax.swing.JLabel();
        addToPendingBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        quantityTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        jScrollPane1.setBorder(null);

        pendingCountTA.setEditable(false);
        pendingCountTA.setColumns(20);
        pendingCountTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingCountTA.setLineWrap(true);
        pendingCountTA.setText("Pending \nItems");
        pendingCountTA.setBorder(null);
        pendingCountTA.setFocusable(false);
        pendingCountTA.setOpaque(false);
        jScrollPane1.setViewportView(pendingCountTA);

        jScrollPane2.setBorder(null);

        pendingDepositTA.setEditable(false);
        pendingDepositTA.setColumns(20);
        pendingDepositTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingDepositTA.setLineWrap(true);
        pendingDepositTA.setText("Pending \nDeposit");
        pendingDepositTA.setBorder(null);
        pendingDepositTA.setFocusable(false);
        pendingDepositTA.setOpaque(false);
        jScrollPane2.setViewportView(pendingDepositTA);

        pendingCountLbl.setText("0");

        pendingDepositLbl.setText("0");

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Add Items");

        typeLbl.setText("Type:");

        sizeLbl.setText("Size:");

        quantityLbl.setText("Quantity:");

        calculatedDepositLbl.setText("Calculated Deposit:");

        typeRBGroup.add(canRB);
        canRB.setText("can");
        canRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canRBActionPerformed(evt);
            }
        });

        typeRBGroup.add(bottleRB);
        bottleRB.setText("bottle");

        sizeRBGroup.add(smallRB);
        smallRB.setText("small");

        sizeRBGroup.add(largeRB);
        largeRB.setText("large");

        addToPendingBtn.setText("Add to pending");
        addToPendingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPendingBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculatedDepositLbl)
                                .addGap(18, 18, 18)
                                .addComponent(displayDepositLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addToPendingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(pendingCountLbl))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(bottleRB)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(125, 125, 125)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pendingDepositLbl)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sizeLbl)
                                            .addComponent(typeLbl))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(canRB)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(smallRB)
                                                .addGap(18, 18, 18)
                                                .addComponent(largeRB)))
                                        .addGap(125, 125, 125)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clearBtn)
                                            .addComponent(backBtn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(195, 195, 195)
                                        .addComponent(welcomeLbl)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantityLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pendingCountLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingDepositLbl)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(sizeLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(canRB)
                            .addComponent(typeLbl)
                            .addComponent(bottleRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smallRB)
                            .addComponent(largeRB))
                        .addGap(10, 10, 10)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayDepositLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToPendingBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityLbl)
                            .addComponent(quantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(calculatedDepositLbl)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canRBActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         returnMenuGUI myreturnMenuGUI = new returnMenuGUI();
           myreturnMenuGUI.setVisible(true);
           dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        typeRBGroup.clearSelection();
        sizeRBGroup.clearSelection();
        quantityTf.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addToPendingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPendingBtnActionPerformed
        // TODO add your handling code here:
        calculatedDepositLbl.setVisible(true);
        displayDepositLbl.setVisible(true);
        int quantity = Integer.parseInt(quantityTf.getText());
        double calculatedDepositValue = 0;
        int pendingCount = 0;
        double pendingDeposit = 0.0;
        if(smallRB.isSelected()){
            calculatedDepositValue = quantity * 0.15;
        } 
        else if(largeRB.isSelected()){
            calculatedDepositValue = quantity * 0.25;
        }
        displayDepositLbl.setText(String.valueOf(calculatedDepositValue));
        pendingCount += quantity;
        pendingDeposit += calculatedDepositValue;
        pendingCountLbl.setText(String.valueOf(pendingCount));
        pendingDepositLbl.setText(String.valueOf(pendingDeposit));

    }//GEN-LAST:event_addToPendingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddItemScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToPendingBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton bottleRB;
    private javax.swing.JLabel calculatedDepositLbl;
    private javax.swing.JRadioButton canRB;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel displayDepositLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton largeRB;
    private javax.swing.JLabel pendingCountLbl;
    private javax.swing.JTextArea pendingCountTA;
    private javax.swing.JLabel pendingDepositLbl;
    private javax.swing.JTextArea pendingDepositTA;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JTextField quantityTf;
    private javax.swing.JLabel sizeLbl;
    private javax.swing.ButtonGroup sizeRBGroup;
    private javax.swing.JRadioButton smallRB;
    private javax.swing.JLabel typeLbl;
    private javax.swing.ButtonGroup typeRBGroup;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
