/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package returndemo;

/**
 *
 * @author Thitsar Thway
 */
public class ReminderScreenGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReminderScreenGUI.class.getName());

    /**
     * Creates new form ReminderScreenGUI
     */
    public ReminderScreenGUI() {
        initComponents();
        setSize(500, 300);
        reminderLbl1.setVisible(false);
        reminderLbl2.setVisible(false);
        reminderTf.setVisible(false);
        milestoneLbl1.setVisible(false);
        milestoneLbl2.setVisible(false);
        milestoneTf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lifetimeCountTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lifetimeDepositTA = new javax.swing.JTextArea();
        lifetimeCountLbl = new javax.swing.JLabel();
        lifetimeDepositLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        reminderCB = new javax.swing.JCheckBox();
        milestoneCB = new javax.swing.JCheckBox();
        reminderLbl1 = new javax.swing.JLabel();
        reminderLbl2 = new javax.swing.JLabel();
        reminderTf = new javax.swing.JTextField();
        milestoneLbl1 = new javax.swing.JLabel();
        milestoneLbl2 = new javax.swing.JLabel();
        milestoneTf = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(null);

        lifetimeCountTA.setEditable(false);
        lifetimeCountTA.setColumns(20);
        lifetimeCountTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lifetimeCountTA.setLineWrap(true);
        lifetimeCountTA.setText("Lifetime Item Count");
        lifetimeCountTA.setBorder(null);
        lifetimeCountTA.setFocusable(false);
        lifetimeCountTA.setOpaque(false);
        jScrollPane1.setViewportView(lifetimeCountTA);

        jScrollPane2.setBorder(null);

        lifetimeDepositTA.setEditable(false);
        lifetimeDepositTA.setColumns(20);
        lifetimeDepositTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lifetimeDepositTA.setLineWrap(true);
        lifetimeDepositTA.setText("Total Deposit Redeemed");
        lifetimeDepositTA.setBorder(null);
        lifetimeDepositTA.setFocusable(false);
        lifetimeDepositTA.setOpaque(false);
        jScrollPane2.setViewportView(lifetimeDepositTA);

        lifetimeCountLbl.setText("0");

        lifetimeDepositLbl.setText("0");

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Stats & Reminders");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        reminderCB.setText("set reminder");
        reminderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminderCBActionPerformed(evt);
            }
        });

        milestoneCB.setText("set milestone");
        milestoneCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milestoneCBActionPerformed(evt);
            }
        });

        reminderLbl1.setText("Remind me when I have");

        reminderLbl2.setText("pending items");

        reminderTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminderTfActionPerformed(evt);
            }
        });

        milestoneLbl1.setText("I aim to return");

        milestoneLbl2.setText("items in total");

        milestoneTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milestoneTfActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(reminderLbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reminderTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reminderLbl2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(milestoneLbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(milestoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(milestoneLbl2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(reminderCB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(milestoneCB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saveBtn)
                                    .addComponent(clearBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lifetimeCountLbl)
                                        .addGap(204, 204, 204))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lifetimeDepositLbl)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(welcomeLbl)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lifetimeDepositLbl))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lifetimeCountLbl))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backBtn)
                        .addComponent(milestoneCB))
                    .addComponent(reminderCB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(clearBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reminderLbl1)
                            .addComponent(reminderLbl2)
                            .addComponent(reminderTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(saveBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(milestoneLbl1)
                            .addComponent(milestoneLbl2)
                            .addComponent(milestoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        returnMenuGUI myreturnMenuGUI = new returnMenuGUI();
        myreturnMenuGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void reminderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminderCBActionPerformed
        // TODO add your handling code here:
        reminderLbl1.setVisible(true);
        reminderLbl2.setVisible(true);
        reminderTf.setVisible(true);
               
    }//GEN-LAST:event_reminderCBActionPerformed

    private void milestoneCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milestoneCBActionPerformed
        // TODO add your handling code here:
        milestoneLbl1.setVisible(true);
        milestoneLbl2.setVisible(true);
        milestoneTf.setVisible(true);
    }//GEN-LAST:event_milestoneCBActionPerformed

    private void reminderTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminderTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reminderTfActionPerformed

    private void milestoneTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milestoneTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milestoneTfActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        reminderCB.setSelected(false);
        milestoneCB.setSelected(false);
        reminderTf.setText("");
        milestoneTf.setText("");

    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReminderScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lifetimeCountLbl;
    private javax.swing.JTextArea lifetimeCountTA;
    private javax.swing.JLabel lifetimeDepositLbl;
    private javax.swing.JTextArea lifetimeDepositTA;
    private javax.swing.JCheckBox milestoneCB;
    private javax.swing.JLabel milestoneLbl1;
    private javax.swing.JLabel milestoneLbl2;
    private javax.swing.JTextField milestoneTf;
    private javax.swing.JCheckBox reminderCB;
    private javax.swing.JLabel reminderLbl1;
    private javax.swing.JLabel reminderLbl2;
    private javax.swing.JTextField reminderTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
