/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package returndemo;

/**
 *
 * @author Thitsar Thway
 */
public class ReturnItemScreenGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnItemScreenGUI.class.getName());

    /**
     * Creates new form AddItemScreenGUI
     */
    public ReturnItemScreenGUI() {
        initComponents();
        setSize(500,300);
        totalReturnedItemsLbl.setVisible(false);
        returnedDepositLbl.setVisible(false);
        calculatedReturnedCountLbl.setVisible(false);
        calculatedReturnedDepositLbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeRBGroup = new javax.swing.ButtonGroup();
        sizeRBGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingCountTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pendingDepositTA = new javax.swing.JTextArea();
        pendingCountLbl = new javax.swing.JLabel();
        pendingDepositLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        returnedItemsLbl = new javax.swing.JLabel();
        smallLbl = new javax.swing.JLabel();
        totalReturnedItemsLbl = new javax.swing.JLabel();
        returnedDepositLbl = new javax.swing.JLabel();
        markReturnedBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        smallTf = new javax.swing.JTextField();
        largeTf = new javax.swing.JTextField();
        largeLbl = new javax.swing.JLabel();
        calculatedReturnedDepositLbl = new javax.swing.JLabel();
        calculatedReturnedCountLbl = new javax.swing.JLabel();
        markAllReturnedBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        jScrollPane1.setBorder(null);

        pendingCountTA.setEditable(false);
        pendingCountTA.setColumns(20);
        pendingCountTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingCountTA.setLineWrap(true);
        pendingCountTA.setText("Pending \nItems");
        pendingCountTA.setBorder(null);
        pendingCountTA.setFocusable(false);
        pendingCountTA.setOpaque(false);
        jScrollPane1.setViewportView(pendingCountTA);

        jScrollPane2.setBorder(null);

        pendingDepositTA.setEditable(false);
        pendingDepositTA.setColumns(20);
        pendingDepositTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingDepositTA.setLineWrap(true);
        pendingDepositTA.setText("Pending \nDeposit");
        pendingDepositTA.setBorder(null);
        pendingDepositTA.setFocusable(false);
        pendingDepositTA.setOpaque(false);
        jScrollPane2.setViewportView(pendingDepositTA);

        pendingCountLbl.setText("0");

        pendingDepositLbl.setText("0");

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Return Items");

        returnedItemsLbl.setText("Enter Returned Items");

        smallLbl.setText("small:");

        totalReturnedItemsLbl.setText("Total returned items:");

        returnedDepositLbl.setText("Returned Deposit:");

        markReturnedBtn.setText("Return Entered Items");
        markReturnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markReturnedBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        largeLbl.setText("large:");

        markAllReturnedBtn.setForeground(new java.awt.Color(255, 51, 51));
        markAllReturnedBtn.setText("Return All Pending");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(welcomeLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnedItemsLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(pendingCountLbl))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalReturnedItemsLbl)
                                    .addComponent(returnedDepositLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calculatedReturnedDepositLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calculatedReturnedCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(smallLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(smallTf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(largeLbl)
                        .addGap(18, 18, 18)
                        .addComponent(largeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pendingDepositLbl)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearBtn)
                            .addComponent(backBtn)))
                    .addComponent(markAllReturnedBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(markReturnedBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingDepositLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markAllReturnedBtn)
                        .addGap(12, 12, 12)
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markReturnedBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingCountLbl)
                        .addGap(7, 7, 7)
                        .addComponent(returnedItemsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smallLbl)
                            .addComponent(smallTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(largeLbl)
                            .addComponent(largeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(totalReturnedItemsLbl))
                            .addComponent(calculatedReturnedCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculatedReturnedDepositLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnedDepositLbl))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         returnMenuGUI myreturnMenuGUI = new returnMenuGUI();
           myreturnMenuGUI.setVisible(true);
           dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void markReturnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markReturnedBtnActionPerformed
        // TODO add your handling code here:
                totalReturnedItemsLbl.setVisible(true);
        returnedDepositLbl.setVisible(true);
        calculatedReturnedCountLbl.setVisible(true);
        calculatedReturnedDepositLbl.setVisible(true);
    }//GEN-LAST:event_markReturnedBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        smallTf.setText("");
        largeTf.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnItemScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel calculatedReturnedCountLbl;
    private javax.swing.JLabel calculatedReturnedDepositLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel largeLbl;
    private javax.swing.JTextField largeTf;
    private javax.swing.JButton markAllReturnedBtn;
    private javax.swing.JButton markReturnedBtn;
    private javax.swing.JLabel pendingCountLbl;
    private javax.swing.JTextArea pendingCountTA;
    private javax.swing.JLabel pendingDepositLbl;
    private javax.swing.JTextArea pendingDepositTA;
    private javax.swing.JLabel returnedDepositLbl;
    private javax.swing.JLabel returnedItemsLbl;
    private javax.swing.ButtonGroup sizeRBGroup;
    private javax.swing.JLabel smallLbl;
    private javax.swing.JTextField smallTf;
    private javax.swing.JLabel totalReturnedItemsLbl;
    private javax.swing.ButtonGroup typeRBGroup;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
