/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package returndemo;

/**
 *
 * @author Thitsar Thway
 */
public class returnMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(returnMenuGUI.class.getName());

    /**
     * Creates new form ReTurnMenuGUI
     */
    public returnMenuGUI() {
        initComponents();
        setSize(500,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        addItemScreenBtn = new javax.swing.JButton();
        returnItemScreenBtn = new javax.swing.JButton();
        reminderScreenBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Welcome to your ReTurn app!");

        addItemScreenBtn.setText("Add Item");
        addItemScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemScreenBtnActionPerformed(evt);
            }
        });

        returnItemScreenBtn.setText("Return Item");
        returnItemScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnItemScreenBtnActionPerformed(evt);
            }
        });

        reminderScreenBtn.setText("Stats & Reminders");
        reminderScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminderScreenBtnActionPerformed(evt);
            }
        });

        homeBtn.setText("Back to Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(welcomeLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reminderScreenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addItemScreenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(returnItemScreenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addComponent(addItemScreenBtn)
                .addGap(18, 18, 18)
                .addComponent(returnItemScreenBtn)
                .addGap(18, 18, 18)
                .addComponent(reminderScreenBtn)
                .addGap(18, 18, 18)
                .addComponent(homeBtn)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemScreenBtnActionPerformed
        // TODO add your handling code here:
        AddItemScreenGUI addItemGUI = new AddItemScreenGUI();
        addItemGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_addItemScreenBtnActionPerformed

    private void returnItemScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnItemScreenBtnActionPerformed
        // TODO add your handling code here:
        ReturnItemScreenGUI returnItemGUI = new ReturnItemScreenGUI();
        returnItemGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnItemScreenBtnActionPerformed

    private void reminderScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminderScreenBtnActionPerformed
        // TODO add your handling code here:
         ReminderScreenGUI reminderGUI = new ReminderScreenGUI();
        reminderGUI.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_reminderScreenBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new returnMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemScreenBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton reminderScreenBtn;
    private javax.swing.JButton returnItemScreenBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
