/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgreturn;

import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Thitsar Thway
 */
public class AddItemScreenGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddItemScreenGUI.class.getName());
    private final ItemLog log;

    /**
     * Creates new form AddItemScreenGUI
     */
    public AddItemScreenGUI() {
        //initialize in constructor
        log = new ItemLog();
        //load object from file
        log.load();
        initComponents();
        //modify UI
        setSize(500, 300);
        getContentPane().setBackground(Color.WHITE);
        //set labels
        calculatedDepositLbl.setVisible(false);
        calculatedDepositDisplay.setVisible(false);
        updateDisplays();
        //display notifications
        log.getReminder().checkReminder(log.getPendingCount(), rootPane);
        log.getReminder().checkMilestone(log.getLifetimeCount(), rootPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeRBGroup = new javax.swing.ButtonGroup();
        sizeRBGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingCountTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pendingDepositTA = new javax.swing.JTextArea();
        pendingCountDisplay = new javax.swing.JLabel();
        pendingDepositDisplay = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        sizeLbl = new javax.swing.JLabel();
        quantityLbl = new javax.swing.JLabel();
        calculatedDepositLbl = new javax.swing.JLabel();
        canRB = new javax.swing.JRadioButton();
        bottleRB = new javax.swing.JRadioButton();
        smallRB = new javax.swing.JRadioButton();
        largeRB = new javax.swing.JRadioButton();
        calculatedDepositDisplay = new javax.swing.JLabel();
        addToPendingBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        quantityTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        pendingCountTA.setEditable(false);
        pendingCountTA.setColumns(20);
        pendingCountTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingCountTA.setLineWrap(true);
        pendingCountTA.setText("Pending \nItems");
        pendingCountTA.setBorder(null);
        pendingCountTA.setFocusable(false);
        pendingCountTA.setOpaque(false);
        jScrollPane1.setViewportView(pendingCountTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 37, 65, -1));

        jScrollPane2.setBorder(null);

        pendingDepositTA.setEditable(false);
        pendingDepositTA.setColumns(20);
        pendingDepositTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingDepositTA.setLineWrap(true);
        pendingDepositTA.setText("Pending \nDeposit");
        pendingDepositTA.setBorder(null);
        pendingDepositTA.setFocusable(false);
        pendingDepositTA.setOpaque(false);
        jScrollPane2.setViewportView(pendingDepositTA);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 37, 65, -1));

        pendingCountDisplay.setText("0");
        getContentPane().add(pendingCountDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 75, -1, -1));

        pendingDepositDisplay.setText("0");
        getContentPane().add(pendingDepositDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 75, -1, -1));

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Add Items");
        getContentPane().add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        typeLbl.setText("Type:");
        getContentPane().add(typeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        sizeLbl.setText("Size:");
        getContentPane().add(sizeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        quantityLbl.setText("Quantity:");
        getContentPane().add(quantityLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        calculatedDepositLbl.setText("Calculated Deposit:");
        getContentPane().add(calculatedDepositLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        typeRBGroup.add(canRB);
        canRB.setText("can");
        canRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canRBActionPerformed(evt);
            }
        });
        getContentPane().add(canRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        typeRBGroup.add(bottleRB);
        bottleRB.setText("bottle");
        getContentPane().add(bottleRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        sizeRBGroup.add(smallRB);
        smallRB.setText("small (150ml-500ml)");
        smallRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallRBActionPerformed(evt);
            }
        });
        getContentPane().add(smallRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        sizeRBGroup.add(largeRB);
        largeRB.setText("large (>500ml-3L)");
        getContentPane().add(largeRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        getContentPane().add(calculatedDepositDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 60, 16));

        addToPendingBtn.setBackground(new java.awt.Color(49, 255, 88));
        addToPendingBtn.setText("Add to pending");
        addToPendingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPendingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToPendingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 132, -1));

        clearBtn.setBackground(new java.awt.Color(49, 255, 88));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 150, -1, -1));

        backBtn.setBackground(new java.awt.Color(49, 255, 88));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 109, -1, -1));

        quantityTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTfActionPerformed(evt);
            }
        });
        getContentPane().add(quantityTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 55, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canRBActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ReturnMenuGUI myreturnMenuGUI = new ReturnMenuGUI();
        myreturnMenuGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        typeRBGroup.clearSelection();
        sizeRBGroup.clearSelection();
        quantityTf.setText("");
        calculatedDepositLbl.setVisible(false);
        calculatedDepositDisplay.setText("");

    }//GEN-LAST:event_clearBtnActionPerformed

    private void addToPendingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPendingBtnActionPerformed

//data validation - cannot add items without entering value
        if (quantityTf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter a number.", "Warning", WARNING_MESSAGE);
            return;
        }

        //get values
        try {
            int quantity = Integer.parseInt(quantityTf.getText().trim());
            double depositPerItem;
            boolean small;
            //assign deposit value based on size chosen
            if (smallRB.isSelected()) {
                depositPerItem = 0.15;
                small = true;
            } else if (largeRB.isSelected()) {
                depositPerItem = 0.25;
                small = false;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please select a size.", "Warning", WARNING_MESSAGE);
                return;
            }
            //update labels
            calculatedDepositLbl.setVisible(true);
            calculatedDepositDisplay.setVisible(true);
            calculatedDepositDisplay.setText(String.format("%.2f", log.addToPending(quantity, depositPerItem, small)));
            updateDisplays();

            //check if reminder and milestone are met
            log.getReminder().checkReminder(log.getPendingCount(), rootPane);
            log.getReminder().checkMilestone(log.getLifetimeCount(), rootPane);
            //save
            log.save();
        } //data validation - catch non-integer inputs
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter an integer");
        }

    }//GEN-LAST:event_addToPendingBtnActionPerformed

    private void quantityTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTfActionPerformed

    private void smallRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallRBActionPerformed

    private void updateDisplays() {
        pendingCountDisplay.setText(String.valueOf(log.getPendingCount()));
        pendingDepositDisplay.setText(String.format("%.2f", log.getPendingDeposit()));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddItemScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToPendingBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton bottleRB;
    private javax.swing.JLabel calculatedDepositDisplay;
    private javax.swing.JLabel calculatedDepositLbl;
    private javax.swing.JRadioButton canRB;
    private javax.swing.JButton clearBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton largeRB;
    private javax.swing.JLabel pendingCountDisplay;
    private javax.swing.JTextArea pendingCountTA;
    private javax.swing.JLabel pendingDepositDisplay;
    private javax.swing.JTextArea pendingDepositTA;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JTextField quantityTf;
    private javax.swing.JLabel sizeLbl;
    private javax.swing.ButtonGroup sizeRBGroup;
    private javax.swing.JRadioButton smallRB;
    private javax.swing.JLabel typeLbl;
    private javax.swing.ButtonGroup typeRBGroup;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
