/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgreturn;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Thitsar Thway
 */
public class ReceiptsGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReceiptsGUI.class.getName());
    private ArrayList<Receipt> rList; //arraylist to save object
    private double depositAmount;
    private String storeName;
    private String storeLocation;

    /**
     * Creates new form ReceiptsGUI
     */
    public ReceiptsGUI() {
        //initialize empty arraylist
        rList = new ArrayList();
        depositAmount = 0.0;
        storeName = new String();
        storeLocation = new String();
        initComponents();
        //modify ui
        setSize(500, 300);
        getContentPane().setBackground(Color.WHITE);
        //load saved receipts
        load();
        //set labels
        updateDisplay();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiptSearchBG = new javax.swing.ButtonGroup();
        depositAmountLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        storeNameLbl = new javax.swing.JLabel();
        storeLocationLbl = new javax.swing.JLabel();
        depositAmountTf = new javax.swing.JTextField();
        storeNameTf = new javax.swing.JTextField();
        storeLocationTf = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        addReceiptBtn = new javax.swing.JToggleButton();
        deleteReceiptBtn = new javax.swing.JToggleButton();
        receiptScrollPane = new javax.swing.JScrollPane();
        receiptTA = new javax.swing.JTextArea();
        deleteAllBtn = new javax.swing.JToggleButton();
        clearBtn = new javax.swing.JButton();
        searchByIDRb = new javax.swing.JRadioButton();
        searchByStoreRb = new javax.swing.JRadioButton();
        searchByLocationRb = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JToggleButton();
        displayAllBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        depositAmountLbl.setText("Deposit Amount");

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Receipts");

        storeNameLbl.setText("Store Name");

        storeLocationLbl.setText("Store Location");

        backBtn.setBackground(new java.awt.Color(49, 255, 88));
        backBtn.setText("Back");
        backBtn.setFocusPainted(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addReceiptBtn.setBackground(new java.awt.Color(49, 255, 88));
        addReceiptBtn.setText("Add Receipt");
        addReceiptBtn.setFocusCycleRoot(true);
        addReceiptBtn.setRequestFocusEnabled(false);
        addReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReceiptBtnActionPerformed(evt);
            }
        });

        deleteReceiptBtn.setBackground(new java.awt.Color(49, 255, 88));
        deleteReceiptBtn.setText("Delete Receipt");
        deleteReceiptBtn.setFocusCycleRoot(true);
        deleteReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReceiptBtnActionPerformed(evt);
            }
        });

        receiptTA.setEditable(false);
        receiptTA.setColumns(20);
        receiptTA.setLineWrap(true);
        receiptTA.setRows(5);
        receiptScrollPane.setViewportView(receiptTA);

        deleteAllBtn.setBackground(new java.awt.Color(49, 255, 88));
        deleteAllBtn.setText("Delete All Receipts");
        deleteAllBtn.setFocusCycleRoot(true);
        deleteAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(49, 255, 88));
        clearBtn.setText("Clear");
        clearBtn.setFocusPainted(false);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        receiptSearchBG.add(searchByIDRb);
        searchByIDRb.setText("Search by ID");

        receiptSearchBG.add(searchByStoreRb);
        searchByStoreRb.setText("Search by Store");

        receiptSearchBG.add(searchByLocationRb);
        searchByLocationRb.setText("Search by Location");

        searchBtn.setBackground(new java.awt.Color(49, 255, 88));
        searchBtn.setText("Search");
        searchBtn.setFocusPainted(false);
        searchBtn.setFocusable(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        displayAllBtn.setBackground(new java.awt.Color(49, 255, 88));
        displayAllBtn.setText("Display All");
        displayAllBtn.setFocusPainted(false);
        displayAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(storeNameLbl)
                                            .addComponent(storeLocationLbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(storeNameTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(storeLocationTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(depositAmountLbl)
                                        .addGap(37, 37, 37)
                                        .addComponent(depositAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addReceiptBtn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(clearBtn)
                                        .addComponent(backBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchByStoreRb)
                                    .addComponent(searchByLocationRb)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchByIDRb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(displayAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteAllBtn)
                                    .addComponent(deleteReceiptBtn)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(welcomeLbl)))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeLbl)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depositAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depositAmountLbl))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(storeNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(storeNameLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(storeLocationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(storeLocationLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addReceiptBtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteReceiptBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayAllBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchByIDRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByStoreRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByLocationRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn))
                    .addComponent(receiptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ReturnMenuGUI myreturnMenuGUI = new ReturnMenuGUI();
        myreturnMenuGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReceiptBtnActionPerformed
        // TODO add your handling code here:
        try {
            //grab value from text fields
            depositAmount = Double.parseDouble(depositAmountTf.getText());
            storeName = storeNameTf.getText();
            storeLocation = storeLocationTf.getText();
            //only add receipt if deposit amount is not zero
            if (depositAmount != 0.0) {
                Receipt r = new Receipt();
                r.setId(rList.size() + 1);
                r.setDepositAmount(depositAmount);
                r.setStoreName(storeName);
                r.setStoreLocation(storeLocation);
                rList.add(r);
            }
        //data validation - catch non-integer inputs
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a deposit amount", "Invalid input", WARNING_MESSAGE);
        }
        updateDisplay();
        save();
    }//GEN-LAST:event_addReceiptBtnActionPerformed

    private void displayAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllBtnActionPerformed
        // TODO add your handling code here:
        displayAllBtn.setRequestFocusEnabled(false);

        updateDisplay();
    }//GEN-LAST:event_displayAllBtnActionPerformed

    private void deleteAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllBtnActionPerformed
        // TODO add your handling code here:
        rList.removeAll(rList);
        updateDisplay();
        save();
    }//GEN-LAST:event_deleteAllBtnActionPerformed

    private void deleteReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReceiptBtnActionPerformed
        // TODO add your handling code here:
        try {
            //delete by id
            int searchTerm = Integer.parseInt(JOptionPane.showInputDialog("Enter id of receipt to delete"));
            boolean found = false;
            for (int i = 0; i < rList.size(); i++) {
                if (searchTerm == rList.get(i).getId()) {
                    rList.remove(i);
                    found = true;
                }
            }
            if (found) {
                JOptionPane.showMessageDialog(null, "Deletion Successful.");
            } else {
                JOptionPane.showMessageDialog(null, "ID not found.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter an ID", "Invalid input", WARNING_MESSAGE);
        } catch (NullPointerException e) {
        }
        updateDisplay();
        save();
    }//GEN-LAST:event_deleteReceiptBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        searchBtn.setRequestFocusEnabled(false);
        //search according to radio button selected
        if (searchByIDRb.isSelected()) {
            try {
                int searchID = Integer.parseInt(JOptionPane.showInputDialog("Enter id of receipt to display"));
                boolean found = false;
                for (Receipt r : rList) {
                    if (searchID == r.getId()) {
                        found = true;

                        receiptTA.setText(
                                "ID: " + r.getId() + "\n"
                                + "Store: " + r.getStoreName() + "\n"
                                + "Location: " + r.getStoreLocation() + "\n"
                                + "Deposit: " + r.getDepositAmount() + "\n"
                                + "--------------------------\n"
                        );
                    }
                }
                if (!found) {
                    JOptionPane.showMessageDialog(null, "ID not found.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter an ID", "Invalid input", WARNING_MESSAGE);
            }
        } else if (searchByStoreRb.isSelected()) {

            String searchTerm = JOptionPane.showInputDialog(null, "Enter store name to display");
            boolean found = false;
            if (searchTerm != null) {
                receiptTA.setText("");
                for (Receipt r : rList) {
                    if (searchTerm.equalsIgnoreCase(r.getStoreName())) {
                        receiptTA.append(
                                "ID: " + r.getId() + "\n"
                                + "Store: " + r.getStoreName() + "\n"
                                + "Location: " + r.getStoreLocation() + "\n"
                                + "Deposit: " + r.getDepositAmount() + "\n"
                                + "--------------------------\n"
                        );
                        found = true;
                    }
                }
                if (!found) {
                    JOptionPane.showMessageDialog(null, "Store name not found.");
                }
            }
        } else if (searchByLocationRb.isSelected()) {

            String searchTerm = JOptionPane.showInputDialog("Enter store location to display");
            boolean found = false;
            if (searchTerm != null) {
                receiptTA.setText("");
                for (Receipt r : rList) {
                    if (searchTerm.equalsIgnoreCase(r.getStoreLocation())) {
                        receiptTA.append(
                                "ID: " + r.getId() + "\n"
                                + "Store: " + r.getStoreName() + "\n"
                                + "Location: " + r.getStoreLocation() + "\n"
                                + "Deposit: " + r.getDepositAmount() + "\n"
                                + "--------------------------\n"
                        );
                        found = true;
                    }
                }
                if (!found) {
                    JOptionPane.showMessageDialog(null, "Store location not found.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a search option.", "No option selected", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateDisplay() {
        receiptTA.setText("");
        for (Receipt r : rList) {
            receiptTA.append(
                    "ID: " + r.getId() + "\n"
                    + "Store: " + r.getStoreName() + "\n"
                    + "Location: " + r.getStoreLocation() + "\n"
                    + "Deposit: " + r.getDepositAmount() + "\n"
                    + "--------------------------\n"
            );
        }
    }

    private void clear() {
        depositAmountTf.setText("");
        storeNameTf.setText("");
        storeLocationTf.setText("");
    }

    private void save() {
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        try {
            outFile = new File("receiptFile.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(rList);
            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }

    private void load() {
        File inFile = new File("receiptFile.data");
        FileInputStream fStream;
        ObjectInputStream oStream;
        try {
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            rList = (ArrayList<Receipt>) oStream.readObject();
            //set text area with each receipt
            for (Receipt r : rList) {
                receiptTA.append(
                        "ID: " + r.getId() + "\n"
                        + "Store: " + r.getStoreName() + "\n"
                        + "Location: " + r.getStoreLocation() + "\n"
                        + "Deposit: " + r.getDepositAmount() + "\n"
                        + "--------------------------\n"
                );
            }
        } catch (FileNotFoundException ex) {
            System.out.println("No file found. Enter data to create file.");

        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReceiptsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addReceiptBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JToggleButton deleteAllBtn;
    private javax.swing.JToggleButton deleteReceiptBtn;
    private javax.swing.JLabel depositAmountLbl;
    private javax.swing.JTextField depositAmountTf;
    private javax.swing.JToggleButton displayAllBtn;
    private javax.swing.JScrollPane receiptScrollPane;
    private javax.swing.ButtonGroup receiptSearchBG;
    private javax.swing.JTextArea receiptTA;
    private javax.swing.JToggleButton searchBtn;
    private javax.swing.JRadioButton searchByIDRb;
    private javax.swing.JRadioButton searchByLocationRb;
    private javax.swing.JRadioButton searchByStoreRb;
    private javax.swing.JLabel storeLocationLbl;
    private javax.swing.JTextField storeLocationTf;
    private javax.swing.JLabel storeNameLbl;
    private javax.swing.JTextField storeNameTf;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
