/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgreturn;

import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;

/**
 *
 * @author Thitsar Thway
 */
public class ReminderScreenGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReminderScreenGUI.class.getName());
    private final ItemLog log;

    /**
     * Creates new form ReminderScreenGUI
     */
    public ReminderScreenGUI() {
        //initialize in constructor
        log = new ItemLog();
        //load object from file
        log.load();
        initComponents();
        //modify UI
        setSize(500, 300);
        getContentPane().setBackground(Color.WHITE);
        //set labels
        updateDisplays();
        //load saved numbers into reminder and milestone text fields
        loadSettings();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lifetimeCountTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lifetimeDepositTA = new javax.swing.JTextArea();
        lifetimeCountDisplay = new javax.swing.JLabel();
        lifetimeDepositDisplay = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        reminderLbl1 = new javax.swing.JLabel();
        reminderLbl2 = new javax.swing.JLabel();
        reminderTf = new javax.swing.JTextField();
        milestoneLbl1 = new javax.swing.JLabel();
        milestoneLbl2 = new javax.swing.JLabel();
        milestoneTf = new javax.swing.JTextField();
        saveSettingsBtn = new javax.swing.JButton();
        resetStatsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(500, 300));

        jScrollPane1.setBorder(null);

        lifetimeCountTA.setEditable(false);
        lifetimeCountTA.setColumns(20);
        lifetimeCountTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lifetimeCountTA.setLineWrap(true);
        lifetimeCountTA.setText("Lifetime Returned Count");
        lifetimeCountTA.setBorder(null);
        lifetimeCountTA.setFocusable(false);
        jScrollPane1.setViewportView(lifetimeCountTA);

        jScrollPane2.setBorder(null);

        lifetimeDepositTA.setEditable(false);
        lifetimeDepositTA.setColumns(20);
        lifetimeDepositTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lifetimeDepositTA.setLineWrap(true);
        lifetimeDepositTA.setText("Total Deposit Redeemed");
        lifetimeDepositTA.setBorder(null);
        lifetimeDepositTA.setFocusable(false);
        lifetimeDepositTA.setOpaque(false);
        jScrollPane2.setViewportView(lifetimeDepositTA);

        lifetimeCountDisplay.setText("0");

        lifetimeDepositDisplay.setText("0");

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Stats & Reminders");

        backBtn.setBackground(new java.awt.Color(49, 255, 88));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(49, 255, 88));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        reminderLbl1.setText("Remind me when I have");

        reminderLbl2.setText("pending items");

        reminderTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminderTfActionPerformed(evt);
            }
        });

        milestoneLbl1.setText("I aim to return");

        milestoneLbl2.setText("items in total");

        milestoneTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milestoneTfActionPerformed(evt);
            }
        });

        saveSettingsBtn.setBackground(new java.awt.Color(49, 255, 88));
        saveSettingsBtn.setText("Save Settings");
        saveSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsBtnActionPerformed(evt);
            }
        });

        resetStatsBtn.setBackground(new java.awt.Color(49, 255, 88));
        resetStatsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetStatsBtn.setText("Reset Lifetime Stats");
        resetStatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetStatsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveSettingsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetStatsBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(milestoneLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(milestoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(milestoneLbl2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(reminderLbl1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(reminderTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(lifetimeCountDisplay)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reminderLbl2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(lifetimeDepositDisplay))
                                                .addGap(20, 20, 20)))
                                        .addGap(18, 18, 18))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(welcomeLbl)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lifetimeCountDisplay))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lifetimeDepositDisplay)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reminderLbl1)
                            .addComponent(reminderLbl2)
                            .addComponent(reminderTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(milestoneLbl1)
                            .addComponent(milestoneLbl2)
                            .addComponent(milestoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveSettingsBtn)
                            .addComponent(resetStatsBtn))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ReturnMenuGUI myreturnMenuGUI = new ReturnMenuGUI();
        myreturnMenuGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void reminderTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminderTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reminderTfActionPerformed

    private void milestoneTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milestoneTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milestoneTfActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();


    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsBtnActionPerformed
        //data validaton - set textfields to zero if blank
        try {
            int reminderThreshold = reminderTf.getText().isBlank()
                    ? 0
                    : Integer.parseInt(reminderTf.getText());
            int milestone = milestoneTf.getText().isBlank()
                    ? 0
                    : Integer.parseInt(milestoneTf.getText());

            //set to log
            log.getReminder().setReminderThreshold(reminderThreshold);
            log.getReminder().setMilestone(milestone);

            String reminderStatus = (reminderThreshold == 0)
                    ? "Not set"
                    : log.getReminder().getReminderThreshold() + " items";

            String milestoneStatus = (milestone == 0)
                    ? "Not set"
                    : log.getReminder().getMilestone() + " items";

            //show message
            JOptionPane.showMessageDialog(rootPane, "Settings saved!\nReminder: " + reminderStatus + "\nMilestone: " + milestoneStatus);
            log.save();
        } //data validation - catch non-integer inputs
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter an integer");
            clear();
        }
    }//GEN-LAST:event_saveSettingsBtnActionPerformed

    private void resetStatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetStatsBtnActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to reset your lifetime stats?", "Reset Lifetime Stats", OK_CANCEL_OPTION);
        if (dialogResult == 0) {
            //set values
            log.setLifetimeCount(0);
            log.setLifetimeDeposit(0);
            //update labels
            updateDisplays();
            //save
            log.save();
        }


    }//GEN-LAST:event_resetStatsBtnActionPerformed
    private void clear() {
        reminderTf.setText("");
        milestoneTf.setText("");
    }

    private void loadSettings() {
        //fill text fields with saved values
        if (log.getReminder().getReminderThreshold() != 0) {
            reminderTf.setText(String.valueOf(log.getReminder().getReminderThreshold()));
        } else {
            reminderTf.setText("");
        }
        if (log.getReminder().getMilestone() != 0) {
            milestoneTf.setText(String.valueOf(log.getReminder().getMilestone()));
        } else {
            milestoneTf.setText("");
        }

    }

    private void updateDisplays() {
        lifetimeCountDisplay.setText(String.valueOf(log.getLifetimeCount()));
        lifetimeDepositDisplay.setText(String.format("%.2f", log.getLifetimeDeposit()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReminderScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lifetimeCountDisplay;
    private javax.swing.JTextArea lifetimeCountTA;
    private javax.swing.JLabel lifetimeDepositDisplay;
    private javax.swing.JTextArea lifetimeDepositTA;
    private javax.swing.JLabel milestoneLbl1;
    private javax.swing.JLabel milestoneLbl2;
    private javax.swing.JTextField milestoneTf;
    private javax.swing.JLabel reminderLbl1;
    private javax.swing.JLabel reminderLbl2;
    private javax.swing.JTextField reminderTf;
    private javax.swing.JButton resetStatsBtn;
    private javax.swing.JButton saveSettingsBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
