/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgreturn;
import maingui.LandingPage;


/**
 *
 * @author Thitsar Thway
 */
public class ReturnMenuGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnMenuGUI.class.getName());

    /**
     * Creates new form ReTurnMenuGUI
     */
    public ReturnMenuGUI() {
        initComponents();
        setSize(500, 300);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        addItemScreenBtn = new javax.swing.JButton();
        returnItemScreenBtn = new javax.swing.JButton();
        reminderScreenBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        receiptsBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Welcome to your ReTurn app!");
        getContentPane().add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 20));

        addItemScreenBtn.setText("Add Item");
        addItemScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemScreenBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addItemScreenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 51, 432, -1));

        returnItemScreenBtn.setText("Return Item");
        returnItemScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnItemScreenBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnItemScreenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 92, 432, -1));

        reminderScreenBtn.setText("Stats & Reminders");
        reminderScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminderScreenBtnActionPerformed(evt);
            }
        });
        getContentPane().add(reminderScreenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 133, 432, -1));

        homeBtn.setText("Back to Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 128, -1));

        receiptsBtn.setText("Receipts");
        receiptsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(receiptsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 174, 432, -1));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OOP vegApp bg2.jpg"))); // NOI18N
        backgroundLbl.setOpaque(true);
        getContentPane().add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 490, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemScreenBtnActionPerformed
        // TODO add your handling code here:
        AddItemScreenGUI addItemGUI = new AddItemScreenGUI();
        addItemGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_addItemScreenBtnActionPerformed

    private void returnItemScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnItemScreenBtnActionPerformed
        // TODO add your handling code here:
        ReturnItemScreenGUI returnItemGUI = new ReturnItemScreenGUI();
        returnItemGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnItemScreenBtnActionPerformed

    private void reminderScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminderScreenBtnActionPerformed
        // TODO add your handling code here:
        ReminderScreenGUI reminderGUI = new ReminderScreenGUI();
        reminderGUI.setVisible(true);
        dispose();

    }//GEN-LAST:event_reminderScreenBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        LandingPage landingGUI = new LandingPage();
        landingGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void receiptsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptsBtnActionPerformed
        // TODO add your handling code here:
        ReceiptsGUI receiptsGUI = new ReceiptsGUI();
        receiptsGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_receiptsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemScreenBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton receiptsBtn;
    private javax.swing.JButton reminderScreenBtn;
    private javax.swing.JButton returnItemScreenBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
