/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgreturn;

import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Thitsar Thway
 */
public class ReturnItemScreenGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnItemScreenGUI.class.getName());
    private final ItemLog log;

    /**
     * Creates new form AddItemScreenGUI
     */
    public ReturnItemScreenGUI() {
        //initialize in constructor
        log = new ItemLog();
        //load object from file
        log.load();
        //modify UI
        initComponents();
        setSize(500, 300);
        getContentPane().setBackground(Color.WHITE);
        //set labels
        hideLabels();
        updateDisplays();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeRBGroup = new javax.swing.ButtonGroup();
        sizeRBGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingCountTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pendingDepositTA = new javax.swing.JTextArea();
        pendingCountDisplay = new javax.swing.JLabel();
        pendingDepositDisplay = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        returnedItemsLbl = new javax.swing.JLabel();
        smallLbl = new javax.swing.JLabel();
        totalReturnedItemsLbl = new javax.swing.JLabel();
        returnedDepositLbl = new javax.swing.JLabel();
        markReturnedBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        smallTf = new javax.swing.JTextField();
        largeTf = new javax.swing.JTextField();
        largeLbl = new javax.swing.JLabel();
        calculatedDepositDisplay = new javax.swing.JLabel();
        calculatedCountDisplay = new javax.swing.JLabel();
        markAllReturnedBtn = new javax.swing.JButton();
        smallCountDisplay = new javax.swing.JLabel();
        largeCountDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        jScrollPane1.setBorder(null);

        pendingCountTA.setEditable(false);
        pendingCountTA.setColumns(20);
        pendingCountTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingCountTA.setLineWrap(true);
        pendingCountTA.setText("Pending \nItems");
        pendingCountTA.setBorder(null);
        pendingCountTA.setFocusable(false);
        pendingCountTA.setOpaque(false);
        jScrollPane1.setViewportView(pendingCountTA);

        jScrollPane2.setBorder(null);

        pendingDepositTA.setEditable(false);
        pendingDepositTA.setColumns(20);
        pendingDepositTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingDepositTA.setLineWrap(true);
        pendingDepositTA.setText("Pending \nDeposit");
        pendingDepositTA.setBorder(null);
        pendingDepositTA.setFocusable(false);
        pendingDepositTA.setOpaque(false);
        jScrollPane2.setViewportView(pendingDepositTA);

        pendingCountDisplay.setText("0");

        pendingDepositDisplay.setText("0");

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLbl.setText("Return Items");

        returnedItemsLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        returnedItemsLbl.setText("Enter Returned Items");

        smallLbl.setText("small:");

        totalReturnedItemsLbl.setText("Total returned items:");

        returnedDepositLbl.setText("Returned Deposit:");

        markReturnedBtn.setBackground(new java.awt.Color(49, 255, 88));
        markReturnedBtn.setText("Return Entered Items");
        markReturnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markReturnedBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(49, 255, 88));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(49, 255, 88));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        largeLbl.setText("large:");

        markAllReturnedBtn.setBackground(new java.awt.Color(49, 255, 88));
        markAllReturnedBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        markAllReturnedBtn.setText("Return All Pending");
        markAllReturnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAllReturnedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(welcomeLbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(smallLbl)
                                    .addComponent(largeLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnedItemsLbl)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(largeTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(smallTf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(smallCountDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(largeCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(totalReturnedItemsLbl)
                                            .addComponent(returnedDepositLbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(calculatedCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(calculatedDepositDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backBtn)
                            .addComponent(clearBtn)
                            .addComponent(markReturnedBtn)
                            .addComponent(markAllReturnedBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(pendingCountDisplay)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pendingDepositDisplay)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingDepositDisplay))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingCountDisplay)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)
                        .addGap(18, 18, 18)
                        .addComponent(markAllReturnedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markReturnedBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(returnedItemsLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(smallTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(largeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smallCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(smallLbl)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(largeCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(largeLbl)))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalReturnedItemsLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(returnedDepositLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculatedCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calculatedDepositDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ReturnMenuGUI myreturnMenuGUI = new ReturnMenuGUI();
        myreturnMenuGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void markReturnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markReturnedBtnActionPerformed
        // TODO add your handling code here:
        //get values
        int smallReturnCount;
        int smallTotal = log.getSmallCount();
        int largeTotal = log.getLargeCount();
        int largeReturnCount;
        int calculatedCount;
        double calculatedDeposit;
        try {
            //return items through small and large text fields
            if (smallTf.getText().isEmpty()) {
                smallReturnCount = 0;
            } else {
                smallReturnCount = Integer.parseInt(smallTf.getText());
                if (smallTotal >= smallReturnCount) {
                    smallTotal -= smallReturnCount;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cannot return more items than pending.", "Invalid input", WARNING_MESSAGE);
                    return;
                }
            }
            if (largeTf.getText().isEmpty()) {
                largeReturnCount = 0;
            } else {
                largeReturnCount = Integer.parseInt(largeTf.getText());
                if (largeTotal >= largeReturnCount) {
                    largeTotal -= largeReturnCount;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cannot return more items than pending.", "Invalid input", WARNING_MESSAGE);
                    return;

                }

            }
            //calculate
            calculatedCount = smallReturnCount + largeReturnCount;
            calculatedDeposit = smallReturnCount * 0.15 + largeReturnCount * 0.25;
            int pendingCount = log.getPendingCount();
            double pendingDeposit = log.getPendingDeposit();

            pendingCount -= calculatedCount;
            pendingDeposit -= calculatedDeposit;
            //set values
            log.setSmallCount(smallTotal);
            log.setLargeCount(largeTotal);
            log.setPendingCount(pendingCount);
            log.setPendingDeposit(pendingDeposit);

            //update labels
            totalReturnedItemsLbl.setVisible(true);
            returnedDepositLbl.setVisible(true);
            calculatedCountDisplay.setVisible(true);
            calculatedDepositDisplay.setVisible(true);
            calculatedCountDisplay.setText(String.valueOf(calculatedCount));
            calculatedDepositDisplay.setText(String.format("%.2f", calculatedDeposit));
            updateDisplays();

            log.save();
        } 
        //data validation - catch non-integer inputs
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter an integer");
        }
        clear();
    }//GEN-LAST:event_markReturnedBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clear();
        hideLabels();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void markAllReturnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAllReturnedBtnActionPerformed
        //dialog asks for confirmation
        int dialogResult = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to return all pending containers?", "Return all items", OK_CANCEL_OPTION);
        if (dialogResult == 0) {
            log.setSmallCount(0);
            log.setLargeCount(0);
            log.setPendingCount(0);
            log.setPendingDeposit(0);
            //update labels
            updateDisplays();
            //save
            log.save();
        }

    }//GEN-LAST:event_markAllReturnedBtnActionPerformed
    private void updateDisplays() {
        smallCountDisplay.setText(String.valueOf(log.getSmallCount()));
        largeCountDisplay.setText(String.valueOf(log.getLargeCount()));
        pendingCountDisplay.setText(String.valueOf(log.getPendingCount()));
        pendingDepositDisplay.setText(String.format("%.2f", log.getPendingDeposit()));
    }

    private void hideLabels() {
        totalReturnedItemsLbl.setVisible(false);
        returnedDepositLbl.setVisible(false);
        calculatedCountDisplay.setVisible(false);
        calculatedDepositDisplay.setVisible(false);
    }

    private void clear() {
        smallTf.setText("");
        largeTf.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnItemScreenGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel calculatedCountDisplay;
    private javax.swing.JLabel calculatedDepositDisplay;
    private javax.swing.JButton clearBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel largeCountDisplay;
    private javax.swing.JLabel largeLbl;
    private javax.swing.JTextField largeTf;
    private javax.swing.JButton markAllReturnedBtn;
    private javax.swing.JButton markReturnedBtn;
    private javax.swing.JLabel pendingCountDisplay;
    private javax.swing.JTextArea pendingCountTA;
    private javax.swing.JLabel pendingDepositDisplay;
    private javax.swing.JTextArea pendingDepositTA;
    private javax.swing.JLabel returnedDepositLbl;
    private javax.swing.JLabel returnedItemsLbl;
    private javax.swing.ButtonGroup sizeRBGroup;
    private javax.swing.JLabel smallCountDisplay;
    private javax.swing.JLabel smallLbl;
    private javax.swing.JTextField smallTf;
    private javax.swing.JLabel totalReturnedItemsLbl;
    private javax.swing.ButtonGroup typeRBGroup;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
